#file: noinspection SpellCheckingInspection

spring:
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Автоматическое создание/обновление таблиц
    show-sql: true      # Показывать SQL запросы

springdoc:
  api-docs:
    enabled: ${SPRING_SWAGGER:true}
  swagger-ui:
    enabled: ${SPRING_SWAGGER:true}

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
        SQL: DEBUG
