#file: noinspection SpellCheckingInspection

spring:
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # Автоматическое создание/обновление таблиц
#    show-sql: true      # Показывать SQL запросы

springdoc:
  api-docs:
    enabled: ${SPRING_SWAGGER:true}
  swagger-ui:
    enabled: ${SPRING_SWAGGER:true}
    tags-sorter: alpha      # Сортировка контроллеров (тегов) по алфавиту
    operations-sorter: alpha # Сортировка методов внутри контроллера по алфавиту

logging:
  level:
    org:
      hibernate:
#        orm:
#          jdbc:
#            bind: TRACE
        SQL: DEBUG
